version: '3'
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Minsk
      - SERVERURL=127.0.0.1
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=172.20.0.3
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "10.13.13.1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      pihole_network:
        ipv4_address: 172.20.0.2

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 5353:53/tcp
      - 5353:53/udp
      - 67:67/udp
      - 80:80
      - 443:443
    environment:
      TZ: 'Europe/Minsk'
      WEBPASSWORD: 'your-password'
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    dns:
      - 127.0.0.1
    networks:
      pihole_network:
        ipv4_address: 172.20.0.3

networks:
  pihole_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
